server.port: 8080

# actuator endpoints
endpoints.enabled: false
endpoints:
  actuator.enabled: true
  autoconfig.enabled: true
  beans.enabled: true
  health.enabled: true
  info.enabled: true
  mappings.enabled: true
  metrics.enabled: true
management.info.git.mode: full

# database
spring:
  datasource:
    url: jdbc:mysql://localhost/cms_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: cms
    password: sding@1SS
  jpa.show-sql: true